### ISSUE TITLE
When will cwe.json be available for CWE List Version 4.16?

### ISSUE THREAD

**Issue by Crashedmind** [CWE-CAPEC/REST-API-wg#4]
CWE List Version is 4.16 per https://cwe.mitre.org/data/downloads.html 

https://github.com/CWE-CAPEC/REST-API-wg/blob/main/json_repo/cwe.json is for 4.15

**Comment by rpiazza** [comment]
Coincidentally, it was updated yesterday.  Sorry for the delay
